/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backtracking;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jocxa
 */
public class Vista_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Inicial
     */
    
    Pruebas pruebas;
    FondoPanel fondo = new FondoPanel();
    
    public Vista_Inicial(Pruebas pruebasE) {
        
        this.setContentPane(fondo);
        initComponents();  

        PintarLabel("Dibujo", this.labelDibujo);
        PintarBoton("Start.png", this.BotonIniciar);
        
        this.pruebas= pruebasE;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public void PintarLabel(String nombre, JLabel label){
        
        ImageIcon imageIcon =new ImageIcon("Imagenes\\"+nombre+".jpg");
        Image imgEscalada = imageIcon.getImage().getScaledInstance(label.getWidth(),label.getHeight(), Image.SCALE_SMOOTH);
        Icon iconEscalado=new ImageIcon(imgEscalada);
        label.setIcon(iconEscalado);
    }
    
    public void PintarBoton(String nombre, JButton b) {
        ImageIcon imgConector = new ImageIcon("Imagenes\\"+nombre);
        b.setIcon(new ImageIcon(imgConector.getImage().getScaledInstance(b.getWidth(), b.getHeight(), 0)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonFuerza = new javax.swing.JButton();
        BotonIniciar = new javax.swing.JButton();
        BotonBackTracking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SpinnerRestricciones = new javax.swing.JSpinner();
        labelDibujo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonFuerza.setText("Fuerza Bruta ");
        BotonFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFuerzaActionPerformed(evt);
            }
        });

        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });

        BotonBackTracking.setText("Backtraking");
        BotonBackTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBackTrackingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Javanese Text", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Resultados: ");

        jLabel2.setFont(new java.awt.Font("Javanese Text", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Restricciones: ");

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Juego de Crimenes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotonFuerza, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(BotonBackTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)))
                        .addComponent(labelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SpinnerRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonIniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(SpinnerRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBackTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BotonFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        
        this.pruebas.IniciarAlgoritmos((int) this.SpinnerRestricciones.getValue());
        
       
    }//GEN-LAST:event_BotonIniciarActionPerformed

    private void BotonFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFuerzaActionPerformed
        //Aca carga todos los datos que se necesitan, probvenientes de el pruebas de esta propia clase
        ArrayList<Nodo[]> posibles = pruebas.posiblesBackTracking;
        ArrayList<Nodo> incorrectas = this.pruebas.incorrectasBackTracking;
        Nodo solucion[] = this.pruebas.solucion;
        int horaInicial[]=this.pruebas.tiempoInicialFuerza;
        int horaFinal[]=this.pruebas.tiempoFinalFuerza;
        
        //Y aca crea un nuevo Vista_Backtracking para ver los resultados, le pasa todos los datos necesarios, por el constructor
        Vista_FuersaBruta vista = new Vista_FuersaBruta(posibles, incorrectas, solucion, horaInicial, horaFinal);

       

    }//GEN-LAST:event_BotonFuerzaActionPerformed

    //Boton para ver los resultados del Backtracking
    private void BotonBackTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBackTrackingActionPerformed
        
        //Aca carga todos los datos que se necesitan, probvenientes de el pruebas de esta propia clase
        ArrayList<Nodo[]> posibles = pruebas.posiblesBackTracking;
        ArrayList<Nodo> incorrectas = this.pruebas.incorrectasBackTracking;
        ArrayList<Nodo[]> restricciones = pruebas.restricciones;
        Nodo solucion[] = this.pruebas.solucion;
        int horaInicial[]=this.pruebas.tiempoInicialBacktracking;
        int horaFinal[]=this.pruebas.tiempoFinalBacktracking;
        
        //Y aca crea un nuevo Vista_Backtracking para ver los resultados, le pasa todos los datos necesarios, por el constructor
        Vista_Backtraking vista = new Vista_Backtraking(posibles, incorrectas, restricciones, solucion, horaInicial, horaFinal);
    }//GEN-LAST:event_BotonBackTrackingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBackTracking;
    public javax.swing.JButton BotonFuerza;
    public javax.swing.JButton BotonIniciar;
    public javax.swing.JSpinner SpinnerRestricciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel labelDibujo;
    // End of variables declaration//GEN-END:variables

  class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/backtracking/fondo.jpg")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    

}
